#  _____     ___ ____
#   ____|   |    ____|      PSX2 OpenSource Project
#  |     ___|   |____       (C)2003, Mavy & Bigboss ( mavy@ps2reality.net , 
#						      bigboss@ps2reality.net )
#  ---------------------------------------------------------------------------


all: build-ps2Perf build-example


clean:
	$(MAKE) -C ps2Perf clean
	$(MAKE) -C example clean
	$(MAKE) -C lib clean


build-ps2Perf:
	$(MAKE) -C ps2Perf

build-example:
	$(MAKE) -C example

