#  _____     ___ ____
#   ____|   |    ____|      PSX2 OpenSource Project
#  |     ___|   |____       (C)2003, Mavy & Bigboss ( mavy@ps2reality.net , 
#						      bigboss@ps2reality.net )
#  ---------------------------------------------------------------------------


EE_LIB = ../lib/libps2Perf.a
EE_OBJS = ps2Perf.o

all: $(EE_LIB)

clean:
	rm -f *.elf *.o *.a

include ../../Makefile.pref
include ../../Makefile.eeglobal
